title: Rohit Sonawane
logo: "/Rohit_photo.jpg?raw=true" 
description: > 
  Full Stack Developer
  <br><br>
  <a href="mailto:rohitsonawane181@gmail.com">rohitsonawane181@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/rohit-sonawane-534652115/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/rstag">Gihub</a> 
theme: jekyll-theme-minimal
